-- vim: ft=lua
setLocal("127.0.0.1:5300")

setACL({"0.0.0.0/0", "::/0"})

local certificate = "/certs/fullchain.pem"
local privateKey = "/certs/privkey.pem"

addTLSLocal("0.0.0.0:8853", certificate, privateKey, {
    provider = "openssl",
    minTLSVersion = "tls1.3",
    maxConcurrentTCPConnections = 1000
})

addDOQLocal("0.0.0.0:8853", certificate, privateKey,
            {idleTimeout = 30, congestionControlAlgo = "cubic"})

newServer({
    address = "172.31.33.20:8054",
    name = "coredns",
    tcpOnly = true,
    checkTCP = true,
    checkInterval = 10
})

setRingBuffersSize(100000, 10)

local abuse = dynBlockRulesGroup()

abuse:setQueryRate(100, 10, "Exceeded query rate", 60, DNSAction.Drop, 50)

abuse:setQTypeRate(DNSQType.ANY, 5, 10, "Exceeded ANY query rate", 60,
                   DNSAction.Drop)

function maintenance() abuse:apply() end
