server {
  listen 443 ssl;
  http2 on;
  if ($server_protocol !~* "HTTP/2") {
    return 444;
  }

  keepalive_timeout 60;
  charset utf-8;

  ssl_certificate /certs/fullchain.pem;
  ssl_certificate_key /certs/privkey.pem;
  ssl_protocols TLSv1.3;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;
  ssl_session_tickets on;

  tcp_nopush on;

  add_header X-Content-Type-Options "nosniff" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header X-Frame-Options SAMEORIGIN always;
  add_header X-XSS-Protection "1; mode=block" always;
  add_header Referrer-Policy "no-referrer";

  fastcgi_hide_header X-Powered-By;

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
      root   /usr/share/nginx/html;
  }

  error_page 401 403 404 /404.html;
  location /dns-query {
  modsecurity_rules '
    SecRuleEngine On
    SecRule REQUEST_URI "@streq /dns-query" "id:100001,phase:1,pass,nolog,ctl:ruleRemoveById=920420"
  ';
    proxy_pass http://172.31.33.20:8053;
  }
}
